FROM node:16

WORKDIR /usr/src/app

# FFmpeg 및 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 10111

CMD ["node", "server.js"]